### ISSUE TITLE
Clear and N

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#11]
0.0.14

When 7 is OFF and we see only scatterplot:

If no sample shown in scatterplot, change N should not generate a sample. If sample is shown, then changing N should, as now, generate a sample with the new N.

When 7 is ON and we see both displays: I think (hope) the spec covers this. From memory, change N gives SCA.

At the moment, clicking Clear gives some inconsistencies with Panels 4, 5, 6. E.g. Panels 5 and 6 close but remain ticked.

I suggest 'Clear' gives:

Panels 4, 5, 6 remain in their open or closed states, with all checkboxes remaining ticked or not. All displayed values (descriptive statistics and slopes) are replaced with '-'. Any displayed lines, including cross through means, disappear (because there are no values for them to represent). It's ok that their boxes remain ticked (if they were already), so that if a further sample is taken, we see all the values and any lines that are ticked.

**Comment by gdcumming** [comment]
0.0.14

'Clear' should not clear the CI checkbox. (I think my efforts to simplify the logic by including lots of SCA in the spec is backfiring in a number of cases. Sorry.)

**Comment by gfmoore** [comment]
>> When 7 is OFF and we see only scatterplot:

>> If no sample shown in scatterplot, change N should not generate a sample. If sample is shown, then changing N should, as now, generate a sample with the new N.

Think I've implemented this now.

>> When 7 is ON and we see both displays: I think (hope) the spec covers this. From memory, change N gives SCA.

I must have missed seeing changing N, but have implemented SCA.

>> Panels 4, 5, 6 remain in their open or closed states, with all checkboxes remaining ticked or not. 

>>All displayed values (descriptive statistics and slopes) are replaced with '-'. Any displayed lines, including cross through means, disappear (because there are no values for them to represent). It's ok that their boxes remain ticked (if they were already), so that if a further sample is taken, we see all the values and any lines that are ticked.

I think I've done this, though the code has become a bit hacky!!

>> 'Clear' should not clear the CI checkbox. (I think my efforts to simplify the logic by including lots of SCA in the spec is backfiring in a number of cases. Sorry.)

No problemo. As always this stuff gets pretty complicated in the code - lots of hacks. As one thing changes it always seems to introduce unanticipated effects. That's why after a certain point I can't see what's happening. There are so many variable names in the code I forget what is what. Pooh bear brain I'm afraid. :) 

We're okay though at the moment.

**Comment by gdcumming** [comment]
0.1.0

Tons of progress :-)

"If no sample shown in scatterplot, change N should not generate a sample. If sample is shown, then changing N should, as now, generate a sample with the new N."

---When Panel 7 is OFF and no sample is displayed in scatterplot, change N does still generate a sample. Tho' its r is not displayed (in three places) and the lines and cross through means are not displayed. Also, the sample is generated if N changed via nudge buttons or typing in a new value, but not if change to N slider. (Same thing if Panel 7 is ON--change N gives SCA but then a new sample is generated in scatterplot.)

**Comment by gfmoore** [comment]
>> "If no sample shown in scatterplot, change N should not generate a sample. 

I can't see this happening?

>>If sample is shown, then changing N should, as now, generate a sample with the new N."

>> When Panel 7 is OFF and no sample is displayed in scatterplot, change N does still generate a sample.

Yes, from the nudge bars and data entry (but not the slider) - oops. Now fixed.

**Comment by gdcumming** [comment]
0.1.5

N and seeing sample in scatterplot seems to work well.

From above, what we'd like when a sample is cleared:
"All displayed values (descriptive statistics and slopes) are replaced with '-'. Any displayed lines, including cross through means, disappear (because there are no values for them to represent). It's ok that their boxes remain ticked (if they were already), so that if a further sample is taken, we see all the values and any lines that are ticked."

----That doesn't work for Panel 7 being clicked ON or OFF. In each case, if sample is visible in scatterplot, that sample is cleared (good) but any lines remain visible, also the cross through means and report of r in scatterplot.

**Comment by gfmoore** [comment]
Okay, I've totally refactored the dance on/off.

I think I've got it, but of course I now leave all tick boxes as they are.
The only way now to get back to a tarting point is to do a refresh or manually untick things. Is this right?

If not perhaps we need to do a refresh on the spec as I'm a bit lost as to what should happen with SCA etc.

Note to untick the all the individual display lines you can untick the actual display lines and retick.

Yeah, I think respec what should happen for each thing (as needed) would really help me. Sorry :(

**Comment by gdcumming** [comment]
0.1.8

Looks good, thanks, closing ...
