### ISSUE TITLE
Display of rho line

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#13]
0.1.5

Display rho line. Click 7 OFF. Then Click 7 ON and rho line is not displayed, tho' sampling with capture can still work -- see red dots and count of captures, despite no rho line. When 7 is clicked on, the rho line should be visible if its box is already ticked.

**Comment by gfmoore** [comment]
Might have fixed this with the last fix 0.1.6 as cannot duplicate it now.

**Comment by gdcumming** [comment]
0.1.8

Thanks, closing ...
