### ISSUE TITLE
Panel 5 X and Y labels disappear

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#14]
0.1.5

Panel 5. Do 'Clear' and 'X' and 'Y' as labels at top of two columns of values disappear, and don't reappear after taking a sample.

Only reappear after Panel 5 closed and reopened.

**Comment by gfmoore** [comment]
I have no idea why I had clear remove the labels. They only disappear if the box closed, and reappear when opened. Man, I'm losing it. ;)  (or did we (or me) once have clear close all panels? Maybe that was it. Anyway, hopefully fixed.

**Comment by gdcumming** [comment]
0.1.8

Thanks, closing...
