### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#15]
0.1.5

As much as possible I'm following the tips already in 'correlation' and 'dances', sometimes with small changes. If no mention below, keep tip as it currently is.

Line 2: dance _r_: "Take samples and see the variation in _r_ from sample to sample"

1 and slider: "Select sample size _N_, within 4 to 300"
_N_ and box under with value: "Size of sample"

2, initial text, and slider: "Use slider to set rho, the correlation in the bivariate normal population"
rho and box under with value: "Population correlation, rho"
_r_ of sample: "Correlation _r_ for displayed sample"

3 as for 'dances'

4 [  ] Population: "A huge sample to illustrate the bivariate normal population"
[  ] Value of _r_ in the figure: "_r_ for this sample"

5 Descriptive statistics [  ]: "Display mean and SD of _X_ and _Y_ for this sample"

6

7 Dance of the _r_ values [  ]: "Open lower display area to display the dance of the _r_ values"

8 Latest sample _r_: "_r_ of latest sample"

9 Display CIs [  ] :"Display CIs on _r_ values"
CI% _C_ [    ]: Use dropdown to select confidence level"
CI on latest _r_ [   ,   ]: "CI on _r_ for latest sample"

10 [  ] rho line: "Display line to mark rho"
[  ] Capture of rho: "Turn on colours to indicate capture, red CIs do not capture rho"
[  ] _r_ heap: "Display heap of _r_ values"
Number of sample taken: "Total number of sample in the current run"
Percent capturing rho: "Percent of CIs in current run that capture rho"

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.1.8

Two tiny things, the second being my error, sorry:

1 and slider: "Select sample size _N_, within 4 to 300" --- remove stuff

10 Number of sample taken: "Total number of samples in the current run" --- make 'samples' plural

**Comment by gfmoore** [comment]
oops, done.

**Comment by gdcumming** [comment]
0.1.9 Thanks, closing...
