### ISSUE TITLE
Control panel spec

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#2]
Here's my first go at a rough mock-up, cobbled together from bits you'll probably recognise.

[Dance r spec 7 Oct 20.docx](https://github.com/gfmoore/esci-dance-r/files/5338762/Dance.r.spec.7.Oct.20.docx)

...not sure if you see it here, or it downloads when you click a link (as for me now in Preview)

I suspect it implies functionality to a large extent, along with the Sample r page in ESCI chapters 14-15 (for the first book). Maybe you can suggest what aspects of functionality I should try to give a better spec for?

**Comment by gfmoore** [comment]
Uhmm, the formatting in the word doc seems to have gone messy on my (old) version of word. Could you save as a pdf please. Most helpful though.

**Comment by gfmoore** [comment]
I think I might need a pdf of the relevant pages from the "old" book as well please. 

I still haven't got my head around what this program is trying to do, now that I'm looking at the spec image (as far as I can interpret it.

So if I press take a sample, what is supposed to happen? Sorry I'm being dense, but I'm feeling a bit "slow" at the moment :)

**Comment by gdcumming** [comment]
Not pretty, but hopefully makes some sense. I could send .docx or doc if that helps.
G

--------------------------------------------
Geoff Cumming, DPhil, Emeritus Professor,
School of Psychology and Public Health, La Trobe University, Melbourne Campus, Victoria, Australia 3086
Email: g.cumming@latrobe.edu.au<mailto:g.cumming@latrobe.edu.au>
Intro textbook: Introduction to The New Statistics: Estimation, Open Science, and Beyond    www.thenewstatistics.com<http://www.thenewstatistics.com>
First book: Understanding The New Statistics: Effect Sizes, Confidence Intervals, and Meta-Analysis   ww.thenewstatistics.com<http://www.thenewstatistics.com/>
Own page: http://www.latrobe.edu.au/she/contact-us/staff/profile?uname=GDCumming
ESCI (Exploratory Software for Confidence Intervals):  www.thenewstatistics.com<http://www.thenewstatistics.com/>
Introduction to the New Statistics is the first statistics textbook to focus on Open Science and the New Statistics. Instructors can obtain a free desk copy at https://www.routledge.com/resources/deskcopy.
Order on Amazon <http://www.amazon.com/dp/1138825522>
[1464879986726_ITNS]


________________________________

**Comment by gfmoore** [comment]
Started to put together the functionality - I think the random selecting of the sample works ok. No dance r stats have yet been worked on, but you may care to make comments about appearance. Might as well get this sorted early on. You also might want to put together the

**Comment by gdcumming** [comment]
That's great, thanks :)

regards,

Gordon Moore
gm@gordonmoore.co.uk

On 07/10/2020 11:50:41, Geoff Cumming <g.cumming@latrobe.edu.au> wrote:
Not pretty, but hopefully makes some sense. I could send .docx or doc if that helps.
G

--------------------------------------------
Geoff Cumming, DPhil, Emeritus Professor,
School of Psychology and Public Health, La Trobe University, Melbourne Campus, Victoria, Australia 3086
Email: g.cumming@latrobe.edu.au [mailto:g.cumming@latrobe.edu.au]
Intro textbook: Introduction to The New Statistics: Estimation, Open Science, and Beyond    www.thenewstatistics.com [http://www.thenewstatistics.com] 
First book: Understanding The New Statistics: Effect Sizes, Confidence Intervals, and Meta-Analysis   ww.thenewstatistics.com [http://www.thenewstatistics.com/]
Own page: http://www.latrobe.edu.au/she/contact-us/staff/profile?uname=GDCumming [http://www.latrobe.edu.au/she/contact-us/staff/profile?uname=GDCumming]
ESCI (Exploratory Software for Confidence Intervals):  www.thenewstatistics.com [http://www.thenewstatistics.com/]
Introduction to the New Statistics is the first statistics textbook to focus on Open Science and the New Statistics. Instructors can obtain a free desk copy at https://www.routledge.com/resources/deskcopy [https://www.routledge.com/resources/deskcopy]. 
Order on Amazon [http://www.amazon.com/dp/1138825522]

[1464879986726_ITNS]

**Comment by gdcumming** [comment]
0.0.1
Looking great already!
Just now I'll focus on the look and layout of the control panel. Overall I'm thinking that it would be good to save vertical space, without making it cramped or resorting to smaller font overall. Requests and./or suggestions, where practical and not too difficult, panel by panel. Hope I'm not getting too finely detailed:

1. Shift blue '_N_' across and down to be centred just above box at right reporting its value. Shift stuff to right a bit, so red '1' can drop down, about to the level of the 0 - 4 - 30 line

2. Top line: "2 Set population correlation rho, see sample correlation _r_" (no radio button)
Blue 'rho' symbol centred just above box at right reporting its value
Value reported for r, in red and not in a white box (which in our convention is for a value set by the user.
Maybe move that reported r value up a little bit, in the quest to save some vertical space.

3. Remove "Controls". Shift the red 3 down a bit, so need to shift the buttons a bit right, maybe smallen the big ones a bit, or the speed slider?

4. Shift lines 2 and 3 out to right and up, so line 2 now in line with "4 Display"

5. Shift the stuff on lines 2-4 to right, so the X and Y can be out to the right, on same line as "5 Descriptive statistics [ ]"

6. Probably not feasible to do a similar shift here. Values of slopes in red please.

7. Fine

8. "r" and value out to the right, on same line as "8 Latest sample"

9. "Display CIs [  ]"  (I see my notes on the spec might have been ambiguous. Sorry. I meant that we need this checkbox, to turn display of CIs on and off, but it has no effect on which control panels are open.
Then on line 2: The drop-down as now, then out to the right the report of CI on latest r

10. Shift line 3 stuff to right and up, into line 2
Perhaps indent the two lines "with lower arm..." and "with upper arm..." a bit more, say by 4-5 characters or whatever you think.

(I'll work on spec for dances tomorrow.)

**Comment by gdcumming** [comment]
0.0.1

I've done more playing with 'sample r' in ESCI, and have had some second thoughts. Let's simplify Panel 10: Please remove these three lines: 'Number of CIs capturing', and the following two lines about capturing with each arm. So we'll have just 'Number of samples taken...' and 'Percent of CIs that capture...'

That should also ease the pressure on vertical space.

**Comment by gfmoore** [comment]
>> Shift blue 'N' across and down to be centred just above box at right reporting its value. Shift stuff to right a bit, so red '1' can drop down, about to the level of the 0 - 4 - 30 line

There's only so much I can do as we are not using absolute positioning here as might be done in Excel. CSS is using relative positioning and as such is designed to create proper control panels.

>> Top line: "2 Set population correlation rho, see sample correlation r" (no radio button)
Blue 'rho' symbol centred just above box at right reporting its value
Value reported for r, in red and not in a white box (which in our convention is for a value set by the user.
Maybe move that reported r value up a little bit, in the quest to save some vertical space.

Don't know where the radio button came from?
The white box IS a data entry box, so you can type in the rho you want. Similar for N above.
To save more space you could move the r of dataset to the right of the text box and have the r label above it

>> Remove "Controls". Shift the red 3 down a bit, so need to shift the buttons a bit right, maybe smallen the big ones a bit, or the speed slider?

Didn't need to change size of anything.

>> Shift lines 2 and 3 out to right and up, so line 2 now in line with "4 Display"

done

>> Shift the stuff on lines 2-4 to right, so the X and Y can be out to the right, on same line as "5 Descriptive statistics [ ]"

done

>> Probably not feasible to do a similar shift here. Values of slopes in red please.

Removed a little padding top and bottom and now red - went and checked correlation and these were red, so not sure what happened when I copied them?

>> "r" and value out to the right, on same line as "8 Latest sample"

done

>> "Display CIs [ ]" (I see my notes on the spec might have been ambiguous. Sorry. I meant that we need this checkbox, to turn display of CIs on and off, but it has no effect on which control panels are open.
Then on line 2: The drop-down as now, then out to the right the report of CI on latest r

No I think I misread the diagram.


>> Shift line 3 stuff to right and up, into line 2
Perhaps indent the two lines "with lower arm..." and "with upper arm..." a bit more, say by 4-5 characters or whatever you think.

Not sure I got this.

Have a look and then see what tweaks you want. I want to get the tweaking out of the way asap as it does my head in :)

**Comment by gfmoore** [comment]
Removed lines from 10

**Comment by gdcumming** [comment]
0.0.6

That all looks great. I can see only one tiny request: Panel 2: '_r_ of sample' not '_r_ of data set' -- which came I guess from correlation.

I'm really loving all this. Looks good, runs v quickly, v responsive...

Closing...

**Comment by gdcumming** [comment]
0.0.9

I remembered one more thing, and have thought a bit more about how dance _r_ should work, mainly aiming for it to be simpler than 'dances' :-)

We need a way to turn the background population pic (upper display area) on and off. I suggest Panel 4: Add a new item above the current two: '[  ] Population'

For the dance, in ESCI the dance (dropping _r_ values possibly with CIs) is in one panel, and the '_r_ heap' is in a separate panel below the dance. Our aim is to combine the two, in the lower display area. So 'dance _r_' works rather like your 'dances'.

I think we need the option to turn off the '_r_ heap', so we can see just the dance _r_ all the way down the display area. I suggest in Panel 10 shifting the '[  ] Capture of rho' (new shortened text) out to the right and up a line, next to '[  ] rho line' (new shortened text). Those two are logically related, so ok I think to be on one line.

Then on second line: '[  ] _r_ heap' lined up under '[  ] rho line'  (All those shortened chunks of text match what's in 'dances'.)

Panel 10, last line: Amend text to be: 'Percent capturing rho'  (Also matching 'dances')

As ever, I'm hoping that's the last of the tedious little tweaks.

**Comment by gfmoore** [comment]
>> We need a way to turn the background population pic (upper display area) on and off. I suggest Panel 4: Add a new item above the current two: '[ ] Population'

done

>> I think we need the option to turn off the 'r heap', so we can see just the dance r all the way down the display area. I suggest in Panel 10 shifting the '[ ] Capture of rho' (new shortened text) out to the right and up a line, next to '[ ] rho line' (new shortened text). Those two are logically related, so ok I think to be on one line.

done

>> I think we need the option to turn off the 'r heap', so we can see just the dance r all the way down the display area. I suggest in Panel 10 shifting the '[ ] Capture of rho' (new shortened text) out to the right and up a line, next to '[ ] rho line' (new shortened text). Those two are logically related, so ok I think to be on one line.

done

>> Then on second line: '[ ] r heap' lined up under '[ ] rho line' (All those shortened chunks of text match what's in 'dances'.)

done

>> Panel 10, last line: Amend text to be: 'Percent capturing rho' (Also matching 'dances')

done

**Comment by gdcumming** [comment]
0.0.11

Great. Thank you. Closing...
