### ISSUE TITLE
Speed control

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#3]
0.0.1

Speed control works well and gives a good range. On my machine, at least, it would be better if it all ran at roughly 1/3 as fast. I.e. slowest speed roughly 1 sample per sec. or a little slower.

BTW, moving the N slider, or the rho slider, gives a *great* effect in the display. I'd never imagined that such would be possible. A big bonus! So quickly responsive!

I'm assuming that having the dance running also, down below, won't slow things up by much, if anything.

**Comment by gfmoore** [comment]
I've slowed it down. The dance may well decrease the speed as it did in dances and depending on what we need it may be significant - I might try a different approach rather than storing information as svg elements, we'll see.

**Comment by gdcumming** [comment]
0.0.6

New slowest and fastest speeds look good to me. And a very good range. Let's call this done for now, and only revisit if sampling seems to change things a lot.

Closing...
