### ISSUE TITLE
Two display areas at right

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#4]
0.0.1

When changing window area and shape, these two display areas generally change very well, the available vertical height split in half, the top area remaining square and being centred above the lower area, which adjusts to be as wide as it can be.

Except that when the right window edge is moved in until the total area available for the two display areas is less wide than it is high. In such cases (as in pic below) the top square area is smaller than it could be and there is spare space below both display areas. Fixable? Probably not a big deal if not, tho' perhaps not ideal on small screens.

There's also some spare space to right of lower display area (approx 1.5cm on my screen) and that's in every case, not just squashed total display area. Also as in pic below. This is no big deal, could easily accept the current as satisficing if hard to adjust.

When dance r is turned off (Panel 7) the square area responds very well. Then itself adjusts well if window size and shape is changed.

Dot size changes well as upper display area changes in size.

But it would be good to have the numbers and labels on the axes larger, ideally without taking up more width (height) for the axis.

Lower area: "Correlation" non-italic and a bit bigger. On both lower and upper axis, "_r_" (black, italic) a bit left of the 0

![dance r pic](https://user-images.githubusercontent.com/55268816/95442526-3945db80-09a7-11eb-892b-34b358972b1b.png)

**Comment by gfmoore** [comment]
Is this better?

**Comment by gdcumming** [comment]
0.0.6

So good, really: so good. One small request: can we have _r_ on the two lower axes a bit bigger? (Doesn't have to be the same font point size as the u/c _X_ and _Y_ in the upper square display.)

Closing...

**Comment by gfmoore** [comment]
Done
