### ISSUE TITLE
Accuracy of sampling

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#5]
0.0.6

Successive random samples from a population with correlation rho should of course have correlations that bounce around--as the dance below will illustrate. With N = 300 the sampling variability of r will be small, giving a 'narrow' dance. With N tiny or small or even medium, variability of r will be enormous then v large then large...

At present that doesn't look as though it's happening. With N = 4, the points leap about, rather too many of them looking to lie well outside the illustrated population. But the r value reported in Panel 2 nearly always equals rho. Sometimes r values bounce around greatly, esp. I think when rho = 0, or v close to 0. But usually r the same or v close to same as rho.

Something weird going on. Maybe copying across some of the code from 'correlation' which includes the 'tweak' so the correlation of the next data set is equal to rho?

P.S. The ESCI 'sample r' page can illustrate the variability in sample r, tho' there is no population illustration to help.

P.P.S. Recall that the X on Y lines in that page are incorrect--my error. Boo.

**Comment by gfmoore** [comment]
Yes, I was wondering what should happen when take a sample is taken and was wondering how this should work!! No worries I will remove the "fix to r" code. 

So let me get this straight.

I take a normal random sample from x and y, apply the formula and display the calculated r on the graph (if checked) and under the slider on panel 2.

Then I display a "blob" for this sample r on the dropping r display?

I know somewhere you explained how to calculate the wings - I also assume it's in the book or pdf. Time to do some reading now I guess. :)

I'll start on that on Monday.

**Comment by gfmoore** [comment]
Actually I did the sampling part now, removing all the fixes:
Just so you can check that I've done it right I've put the code here. I'm too busy at the moment watching the Giro so I haven't checked the maths :)  lol

function createScatters() {

    scatters      = [];
    xscatters     = [];
    yscatters     = [];

    let coeff = Math.sqrt(1 - rs*rs);

    for (i = 0; i < N1; i += 1) {     //N1 is number in the sample
      xs = jStat.normal.sample( 0, 1 );
      ys = jStat.normal.sample( 0, 1 );

      //adjust
      ys = (rs * xs) + (coeff * ys);   //this is the bit to check  (rs is the selected r from the slider)

      xscatters.push(xs);
      yscatters.push(ys);
      scatters.push( {x: xs, y: ys} );   //don't worry about this duplication of the two arrays into one - there was a reason for it and now I forget what it was.
    }

    //now get corr coeff of sample
    r = jStat.corrcoeff( xscatters, yscatters );
  }

**Comment by gdcumming** [comment]
0.0.9

That calculation looks correct to me. It matches what's in ESCI, and my memory of what we discussed before. It also seems to make sense, e.g. giving correct values for rho (your rs) = 0 or 1.

Also, as I watch samples of dots in relation to the population pic, all seems fine. As if we are taking a random selection of the dots in the population. Only rare ones fall what looks like 'beyond' the population cloud.

Also, the three lines all look to be doing the right thing as successive samples are taken.

That's mainly just my eyeballing, but all does seem to fit. Goodie.

Calculation of the CI on r: Yep, details in that pdf. Pp 387-390. Formulas on p. 388. Hopefully not too complicated, given the calculation resources you seem to have to hand. (Natural log, exponentiation, is as complex as it gets.)

**Comment by gdcumming** [comment]
0.0.11

Discussing CIs elsewhere. Closing here...
