### ISSUE TITLE
The population

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#7]
0.0.11

Population switching on/off is great. Population looks good. I guess you have played with larger and smaller numbers of points--several thousand? Also darker and fainter circles? I'm not asking that you show us lots of options, just that you've had a play. To my eye, the circles are excellent for size and dark/faint. Works both for the small upper square and the larger square when dance r turned off. But I'm wondering whether a larger number of circles would give a more pronounced dense central ellipse, but still with clear shading in all directions? Needs to work well for values of rho from 0 to 1. Happy if you do the playing and report.

One reason for opening this issue was to raise the question of the population changing (a whole new giant sample taken, I guess) whenever rho is changed. In particular, when I drag the rho slider the population itself 'dances'. On further thought, different rho does give a different population (of course), so perhaps that dancing is inevitable, or at least is the easiest way to get a population with the new rho? Otherwise we're back to the tweaking that we used in 'correlation' to get a data set with a specified r. (Take a random sample, then tweak...) Would that be feasible/easy on a population scale? So if rho is changed all the existing points in the population shift a tiny bit, to give us the new rho, rather than be replaced with a whole new set of points. If it worked, I suspect it would look super-cool. If not practical, we'll satisfice with the dancing population, if necessary explaining why.

It's great that the population remains unchanged as N is changed.

**Comment by gfmoore** [comment]
>> I guess you have played with larger and smaller numbers of points--several thousand? Also darker and fainter circles?

Haven't tweaked anything. If you want I could temporarily add some simple controls for you to fiddle with and then I can hard code the values? What would you like?

>> Otherwise we're back to the tweaking that we used in 'correlation' to get a data set with a specified r. (Take a random sample, then tweak...)

I can implement this if you want. However, the way I implement this is to create an array of random points then display it. I am not displaying one point at a time and then adjusting that point. I didn't do that with correlation either!

Maybe something to look at later, much later.

**Comment by gdcumming** [comment]
0.0.14

More pop playing, it's fun. 

Number of points in pop: If not too difficult, I'd love to see what larger numbers look like, over the 0-1 range of rho. Say 50%, 100% 150% more, or finer steps if that's easy. Thanks. (I'm happy to stick with the size and colour of the little circles, as you chose.)

Tweaking--yep, let's leave this as is. No worries.

**Comment by gfmoore** [comment]
Added textbox at top, under breadcrumbs. Just enter the number of points, default = 5000 and hit enter. Does a Clear.

**Comment by gdcumming** [comment]
0.1.0

Maybe you should consider putting this (maybe all of esci web) up on STEAM! Might the world enjoy getting in on the fun?

Thanks for the pop number option. I've played with quite a few values. I'll go with 8000. Yes, if much more it's slower but I don't think we gain anything. 8K definitely better than 5K to my eye. Considering large and small scatterplots, and the full range of rho, I think 8K is best.

I now think that the population being generated fresh with any rho change is a feature, not a bug. Even with such an enormous sample size the pattern dances, tho' the overall shape and densities are pretty much the same. Yet another illustration of the main message of 'dance r' -- that's there is massive sampling variability in the correlation!

One glitch: When 'Population' is clicked on or off in Panel 4, there is no action, until rho or N is changed, or Panel 7 open/closed, or Clear is clicked, or r heap on/off.

**Comment by gfmoore** [comment]
>>  I'll go with 8000

done

>> One glitch: When 'Population' is clicked on or off in Panel 4, there is no action, until rho or N is changed, or Panel 7 open/closed, or Clear is clicked, or r heap on/off.

I'm assuming by this that you want a new population to be generated? I thought that once generated for a particular rho it was kept static?

Clicking Population on or off just hides or shows this background population!

Perhaps I missed a spec for this button. Could you republish please.

**Comment by gfmoore** [comment]
Ahhh, found what you mean. I think this now works.

**Comment by gdcumming** [comment]
0.1.5

Pop looks good and works well. Closing
