### ISSUE TITLE
How 'Clear' should work, and related issues

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-dance-r#8]
0.0.11

This is a more detailed spec for Clear, with some changes from what's in the initial spec (#6)

Click 'Clear' should give:
--sample is cleared from the scatterplot (matches 'dances', and allows us to see and play with just the pop picture)
--the value reported for _r_ of latest sample (Panels 2 and 8) is cleared; it should be just '.' (decimal point) or maybe dash, but not .00
--in the scatterplot, if 'Value of _r_ in figure' is turned on, then 'Clear' causes that '_r_ = .xx' to disappear, which is fine.
--r value dots and CIs, both dance and heap, are cleared in the lower display
--counts of samples taken and % capture are both reset to zero

What should not happen on 'Clear': 
--no resetting of _N_ to 50 (or 4), so no change to whatever the current _N_ is
--no resetting of rho to .50, so no change to whatever the current rho is
(At present both those resettings seem to happen, although not always immediately apparent in slider positions)
--no regeneration of the population pic (after all, rho hasn't changed)

When Panel 7 is clicked OFF, don't follow the closing of the lower area and general clearing with taking one new sample to be shown in the scatterplot. We should see the enlarged scatterplot without a sample displayed.

**Comment by gfmoore** [comment]
>> --sample is cleared from the scatterplot (matches 'dances', and allows us to see and play with just the pop picture)

done

>> --the value reported for r of latest sample (Panels 2 and 8) is cleared; it should be just '.' (decimal point) or maybe dash, but not .00

Done and on initial display. Will only display if a sample is taken. This could be by change in N though?

At the moment moving N is causing a sample to be taken, but doesn't cause a dropping r sample to be displayed.

>> --in the scatterplot, if 'Value of r in figure' is turned on, then 'Clear' causes that 'r = .xx' to disappear, which is fine.

ok, 

>> --no resetting of N to 50 (or 4), so no change to whatever the current N is

done

>> --no resetting of rho to .50, so no change to whatever the current rho is

done

>> --no regeneration of the population pic (after all, rho hasn't changed)

ok


>> When Panel 7 is clicked OFF, don't follow the closing of the lower area and general clearing with taking one new sample to be shown in the scatterplot. We should see the enlarged scatterplot without a sample displayed.

So whenever Panel 7 is clicked off (or on) there is no sample displayed. Is this correct for clicking on?
For instance I may have a sample displayed, if I click dances on, then it clears the sample. (As I go through the SCA stuff this question may get resolved!
